name: Continuous Integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.2'  # Updated to match VirtLang-Go requirements

      - name: Update dependencies
        run: go mod tidy

      - name: Build
        run: |
          # Set development version for CI builds
          VERSION="dev-$(git rev-parse --short HEAD)"
          go build -v -ldflags="-X main.Version=$VERSION" ./...

      - name: Test
        run: go test -v ./...